# Change these first
owner: Haoqi7 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Let's Cook
    url: https://cook.wasenk.cf/
  - name: File Transfer
    url: https://code.haoqiyong.cf/
  - name: File文件传递柜
    url: https://file.haoda7.repl.co
  - name: Drop
    url: https://drop.hao77.repl.co/
  - name: memos备忘录
    url: https://memos-on-replit.hao77.repl.co/
  - name: Note便签
    url: https://note.haoqiyun.ml/ 
  - name: Bill账单
    url: https://bill.wasenk.cf/
  - name: All网盘搜索
    url: https://search.haoqiyun.ml/
  - name: One网盘
    url: https://pan.haoqiyun.tk/
  - name: OneDrive
    url: https://pan.wasenk.cf/zh-CN/
  - name: Alist网盘
    url: https://pan.haoda.repl.co/
  - name: Cloudreve 网盘
    url: https://one.haoda.repl.co/
  - name: Stable Diffusion
    url: https://haoqi7-images.hf.space/
  - name: SearchIEEE文献
    url: https://haoqi7-research.hf.space/
  - name: AI对话
    url: https://haoqi7-question.hf.space/
  - name: AI绘画
    url: https://haoqi7-draw.hf.space/
  - name: Chat匿名聊天
    url: https://chat.hao77.repl.co/
  - name: Google Search
    url: https://google.haoqiyun.tk/
  - name: Typecho博客
    url: https://blog.haoqiyong.cf/
  - name: Butterfly博客
    url: https://haoqiyun.tk/
  - name: Matery博客
    url: https://www.haoqiyung.ml/
  - name: Rabbit博客
    url: https://haoqiyun.ml/    
  - name: NAS-state
    url: https://nas.wasenk.cf
  - name: My文档
    url: https://wasenk.cf
  - name: Chinese诗歌
    url: https://haoqi7.github.io/poetry/
  - name: EverydayNews
    url: https://haoqi7.github.io/EverydayNews
  - name: Day's早报
    url: https://news.haoqiyun.ml/
  - name: Weibo热搜榜
    url: https://haoqi7.github.io/weibo-search/
  - name: Book search
    url: https://book.haoda7.repl.co/
  - name: Online reader
    url: https://reader.hao77.repl.co/
  - name: Nav导航网站
    url: https://nav.haoqiyun.ml/
  - name: Learn Only导航
    url: https://nav.wasenk.cf/
  - name: Games合集
    url: https://game.haoqiyun.tk/
  - name: five-Chess
    url: https://haoqi7.github.io/five-Chess/
  - name: Chinese-chess
    url: https://haoqi7.github.io/Chinese-chess
  - name: catch-cat
    url: https://haoqi7.github.io/catch-cat
  - name: Music
    url: https://music.haoqiyong.cf
  - name: YesPlayMusic
    url: https://music.wasenk.cf/
  - name: BiYingWallPaper
    url: https://haoqi7.github.io/BiYingWallPaper/
  - name: GitHub文件加速
    url: https://git.haoqiyong.cf/
  - name: OneLine Tool
    url: https://haoqi7.github.io/online-tools/
  - name: online抠图
    url: https://image.haoqi7.repl.co/
  - name: TUku
    url: https://tu.hao77.repl.co/
  - name: API代理
    url: https://proxy.haoqiyun.tk/
  - name: rsshub
    url: https://rss.haoqiyung.ml/
  - name: Translate
    url: https://translate.haoqiyung.ml
  - name: Deepl
    url: https://deep.haoda.repl.co/
  - name: Deeplx
    url: https://deep.haoda7.repl.co/
  - name: fy
    url: https://fy.haoda.repl.co/
  - name: Bing Straslate API
    url: https://fy.haoda7.repl.co/
  - name: TXT-convert
    url: https://haoqiyung.github.io/web-txt-convert/
  - name: Ipfs
    url: https://haoqiyung.ml/ipfs/
  - name: cs
    url: https://cs.haoqiyong.cf
  - name: count不蒜子
    url: https://count.haoqi7.repl.co/


status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HaoQiのStatus Website
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
