# Change these first
owner: Haoqi7 # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: Let's Cook
    url: https://cook.wasenk.cf/
  - name: push
    url: https://server.haoqiyun.tk/
  - name: Note便签
    url: https://note.haoqiyun.tk/ 
  - name: Bill账单
    url: https://bill.wasenk.cf/
  - name: All网盘搜索
    url: https://search.haoqiyun.tk/
  - name: Google Search
    url: https://google.haoqiyun.tk/
  - name: Butterfly博客
    url: https://haoqiyun.tk/
  - name: Matery博客
    url: https://haoqiyung.github.io/
  - name: Rabbit博客
    url: https://haoqi7.github.io/    
  - name: NAS-state
    url: https://nas-state.vercel.app/
  - name: My文档
    url: https://wasenk.cf
  - name: Chinese诗歌
    url: https://haoqi7.github.io/poetry/
  - name: EverydayNews
    url: https://haoqi7.github.io/EverydayNews
  - name: Day's早报
    url: https://news.haoqiyun.tk/
  - name: Weibo热搜榜
    url: https://haoqi7.github.io/weibo-search/
  - name: Learn Only导航
    url: https://nav.wasenk.cf/
  - name: Games合集
    url: https://game.haoqiyun.tk/
  - name: five-Chess
    url: https://haoqi7.github.io/five-Chess/
  - name: Chinese-chess
    url: https://haoqi7.github.io/Chinese-chess
  - name: catch-cat
    url: https://haoqi7.github.io/catch-cat
  - name: YesPlayMusic
    url: https://music.wasenk.cf/
  - name: BiYingWallPaper
    url: https://haoqi7.github.io/BiYingWallPaper/
  - name: GitHub文件加速
    url: https://git.haoqiyong.cf/
  - name: OneLine Tool
    url: https://haoqi7.github.io/online-tools/
  - name: API代理
    url: https://proxy.haoqiyun.tk/
  - name: rsshub
    url: https://rss.wasenk.cf/
  - name: Translate
    url: https://translate.wasenk.cf/
  - name: TXT-convert
    url: https://haoqiyung.github.io/web-txt-convert/
  - name: Ipfs
    url: https://haoqiyung.github.io/ipfs/



status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  baseUrl: /uptime
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: HaoQiのStatus Website
  introTitle: "**Uptime** is the open-source uptime monitor and status page, powered entirely by GitHub."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
